const PB={VERSION:"1.0.0",SHEETS:{LOG:"PB_MIRROR_LOG",STATE:"PB_MIRROR_STATE"},AGENT_SHEET:"AE_AGENTS",INTAKE_SHEET:"LI_INTAKE",LEADS_SHEET:"AE_LEADS"};
function PB_initialize(){const ss=workbook_();PB_createSheet_(ss,PB.SHEETS.LOG,["MirrorID","LeadID","AgentID","AgentName","SourceWorkbookID","SourceSheet","Status","Details","MirroredAt"]);PB_createSheet_(ss,PB.SHEETS.STATE,["AgentID","SourceWorkbookID","SourceSheet","LastProcessedRow","UpdatedAt"]);return {success:true,version:PB.VERSION};}
function PB_createSheet_(ss,name,headers){let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0){sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1);}return sh;}
function PB_objects_(sheet){if(!sheet||sheet.getLastRow()<2)return[];const v=sheet.getDataRange().getValues();const h=v.shift().map(x=>String(x||"").trim());return v.filter(r=>r.some(x=>String(x||"").trim()!=="")).map((r,i)=>{const o={_row:i+2};h.forEach((k,j)=>o[k]=r[j]);return o;});}
function PB_firstValue_(o,names){for(let i=0;i<names.length;i++){const k=names[i];if(Object.prototype.hasOwnProperty.call(o,k)&&String(o[k]||"").trim()!=="")return o[k];}return "";}
function PB_normalizeEmail_(v){return String(v||"").trim().toLowerCase();}
function PB_normalizePhone_(v){return String(v||"").replace(/\D/g,"");}
function PB_makeLeadID_(lead){const seed=PB_normalizeEmail_(lead.Email)+"|"+PB_normalizePhone_(lead.Phone)+"|"+String(lead.Name||"");const d=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,seed,Utilities.Charset.UTF_8);const hex=d.map(b=>{const v=b<0?b+256:b;return("0"+v.toString(16)).slice(-2);}).join("");return "LD-"+hex.substring(0,12).toUpperCase();}
function PB_log_(lead,agent,sourceId,sourceSheet,status,details){workbook_().getSheetByName(PB.SHEETS.LOG).appendRow(["PB-"+Utilities.getUuid().substring(0,8).toUpperCase(),lead.LeadID||"",agent.AgentID||"",agent.AgentName||"",sourceId||"",sourceSheet||"",status,details||"",new Date()]);}
