/** Auto-generated by MelroseOS Installer 4.2.0. */
var M4_DISTRIBUTED_CONFIG = Object.freeze({
  WORKBOOK_KEY: 'WEBSITE',
  SPREADSHEET_ID: '1Ml9wEEz_gi30i8Js3iMJeycYy_nnrVv6KYD22g9aVhc',
  CORE_SPREADSHEET_ID: '1W-32zYjyttQQS81UnvzJFz9yhp58YUKpTM0Kw0bfK64',
  VERSION: '4.2.0'
});

function getMelroseDistributedWorkbookConfig() {
  return {
    success: true,
    workbookKey: M4_DISTRIBUTED_CONFIG.WORKBOOK_KEY,
    spreadsheetId: M4_DISTRIBUTED_CONFIG.SPREADSHEET_ID,
    coreSpreadsheetId: M4_DISTRIBUTED_CONFIG.CORE_SPREADSHEET_ID,
    version: M4_DISTRIBUTED_CONFIG.VERSION
  };
}