<#
MelroseOS Enterprise
Module: PKG-007_PackageInstaller.ps1
Release: MOS5-018
Placeholder module generated by installer.
#>

$ErrorActionPreference='Stop'
Write-Host "[PASS] PKG-007_PackageInstaller.ps1 Ready"
exit 0
